# 뉴스 제목-분류 크롤링

In [1]:
#정치 0
pol_url = 'https://news.naver.com/main/main.nhn?mode=LSD&mid=shm&sid1=100'
#경제 1
eco_url = 'https://news.naver.com/main/main.nhn?mode=LSD&mid=shm&sid1=101'
#사회 2
soc_url = 'https://news.naver.com/main/main.nhn?mode=LSD&mid=shm&sid1=102'
#생활/문화 3
lif_url = 'https://news.naver.com/main/main.nhn?mode=LSD&mid=shm&sid1=103'
#IT/과학 4
it_url = 'https://news.naver.com/main/main.nhn?mode=LSD&mid=shm&sid1=105'

class_list = ['pol', 'eco', 'soc', 'lif', 'it']
url_list = [pol_url, eco_url, soc_url, lif_url, it_url]
target_class = ['cluster_text_headline nclicks(cls_pol.clsart)', 'cluster_text_headline nclicks(cls_eco.clsart)',
               'cluster_text_headline nclicks(cls_nav.clsart)', 'cluster_text_headline nclicks(cls_lif.clsart)',
               'cluster_text_headline nclicks(cls_sci.clsart)']

print('done')

done

In [2]:
#데이터셋 확보를 위해 주기적으로 돌려줄 것.

from bs4 import BeautifulSoup
import requests
import time
import re
import csv
import pandas as pd

for i, url in enumerate(url_list) :
    res = requests.get(url_list[i], headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36'
    })
    soup = BeautifulSoup(res.text, 'html.parser')
    result = soup.findAll('a', class_=target_class[i])
    
    for k, title in enumerate(result) : 
        result[k] = re.sub('<.+?>','',str(title)) #태그 제거
        result[k] = re.sub('[^ㄱ-ㅎㅏ-ㅣ가-힣 ]', '', result[k]) #한글, 띄어쓰기 빼고 다 제거
    
    result_df = pd.DataFrame(result, columns=['title'])
    result_df['type'] = i
    
    exist_df = pd.read_csv('data/'+class_list[i]+'.csv')
    result_df = pd.concat([exist_df, result_df])
    
    result_df.drop(['Unnamed: 0'], axis=1, inplace=True) #합쳐지면서 이상한 열이 생기는 거 삭제
    
    result_df.to_csv('data/'+class_list[i]+'.csv', mode='w', sep=',', na_rep='NaN')
    
    print(class_list[i], 'is saved!')
    time.sleep(3) #3초간 쉼으로써 크롤링 감지 및 차단 방지

pol is saved!
eco is saved!
soc is saved!
lif is saved!
it is saved!

In [5]:
#저장된 데이터 확인

for strs in class_list :
    df_data = pd.read_csv('data/'+strs+'.csv')
    print(df_data.shape)
    print(df_data)
    print(df_data['title'], df_data['type'])

(200, 7)
     Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1  \
0             0           0.0             0.0               0.0
1             1           1.0             1.0               1.0
2             2           2.0             2.0               2.0
3             3           3.0             3.0               3.0
4             4           4.0             4.0               4.0
..          ...           ...             ...               ...
195          35           NaN             NaN               NaN
196          36           NaN             NaN               NaN
197          37           NaN             NaN               NaN
198          38           NaN             NaN               NaN
199          39           NaN             NaN               NaN

     Unnamed: 0.1.1.1.1                           title  type
0                   0.0                에서 쑥 들어간 홍남기 경질론     0
1                   1.0   민주당 대통령 말씀 당과 일치재난지원금 선별보편 함께     0
2                   2.0     선별이냐 보편이냐차 재난지원금 문 대통령의 속내는     0
3                   3.0   차 재난지원금 선별보편 병행 관철  선별 차등지급해야     0
4                   4.0       진성준 일체 신체접촉 없어민형사 책임 물을 것     0
..                  ...                             ...   ...
195                 NaN   안철수금태섭 토론여론조사 방식 두고 입장 차협상 난항     0
196                 NaN     당정 내달 부동산대책 후속입법현금청산 위헌 아니다     0
197                 NaN        당정 현금청산 위헌 아냐대책 월 입법 속도전     0
198                 NaN      우상호 새천년  사건 제 인생 가장 후회하는 일     0
199                 NaN     이언주  우상호 때아닌 단란주점 접대부  공방 왜     0

[200 rows x 7 columns]
0                    에서 쑥 들어간 홍남기 경질론
1       민주당 대통령 말씀 당과 일치재난지원금 선별보편 함께
2         선별이냐 보편이냐차 재난지원금 문 대통령의 속내는
3       차 재난지원금 선별보편 병행 관철  선별 차등지급해야
4           진성준 일체 신체접촉 없어민형사 책임 물을 것
                    ...
195     안철수금태섭 토론여론조사 방식 두고 입장 차협상 난항
196       당정 내달 부동산대책 후속입법현금청산 위헌 아니다
197          당정 현금청산 위헌 아냐대책 월 입법 속도전
198        우상호 새천년  사건 제 인생 가장 후회하는 일
199       이언주  우상호 때아닌 단란주점 접대부  공방 왜
Name: title, Length: 200, dtype: object 0      0
1      0
2      0
3      0
4      0
      ..
195    0
196    0
197    0
198    0
199    0
Name: type, Length: 200, dtype: int64
(150, 7)
     Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1  \
0             0           0.0             0.0               0.0
1             1           1.0             1.0               1.0
2             2           2.0             2.0               2.0
3             3           3.0             3.0               3.0
4             4           4.0             4.0               4.0
..          ...           ...             ...               ...
145          25           NaN             NaN               NaN
146          26           NaN             NaN               NaN
147          27           NaN             NaN               NaN
148          28           NaN             NaN               NaN
149          29           NaN             NaN               NaN

     Unnamed: 0.1.1.1.1                             title  type
0                   0.0      안갯속 빠진 애플카 협업잠정 중단에 무게인터뷰투데이     1
1                   1.0  테슬라 비트코인 조원 넘게 투자이 말에 비트코인 만원 돌파     1
2                   2.0    테슬라 조 규모 비트코인 매입전기차 비트코인 결제 검토     1
3                   3.0     테슬라 이어 애플도 비트코인 사들이면 예상 시나리오는     1
4                   4.0               주당 천원 배당주주 환원 지속 확대     1
..                  ...                               ...   ...
145                 NaN               진격의   공장 이어 에 거점 구축     1
146                 NaN       테슬라 덕분에 비트코인 사상 첫 국내 천만원 돌파     1
147                 NaN            비트코인도 테슬라 효과국내 가상화폐 급등     1
148                 NaN                 전자화학 덕분에 영업이익  증가     1
149                 NaN                 지난해 영업이익 조억원전년보다      1

[150 rows x 7 columns]
0          안갯속 빠진 애플카 협업잠정 중단에 무게인터뷰투데이
1      테슬라 비트코인 조원 넘게 투자이 말에 비트코인 만원 돌파
2        테슬라 조 규모 비트코인 매입전기차 비트코인 결제 검토
3         테슬라 이어 애플도 비트코인 사들이면 예상 시나리오는
4                   주당 천원 배당주주 환원 지속 확대
                     ...
145                 진격의   공장 이어 에 거점 구축
146         테슬라 덕분에 비트코인 사상 첫 국내 천만원 돌파
147              비트코인도 테슬라 효과국내 가상화폐 급등
148                   전자화학 덕분에 영업이익  증가
149                   지난해 영업이익 조억원전년보다
Name: title, Length: 150, dtype: object 0      1
1      1
2      1
3      1
4      1
      ..
145    1
146    1
147    1
148    1
149    1
Name: type, Length: 150, dtype: int64
(200, 7)
     Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1  \
0             0           0.0             0.0               0.0
1             1           1.0             1.0               1.0
2             2           2.0             2.0               2.0
3             3           3.0             3.0               3.0
4             4           4.0             4.0               4.0
..          ...           ...             ...               ...
195          35           NaN             NaN               NaN
196          36           NaN             NaN               NaN
197          37           NaN             NaN               NaN
198          38           NaN             NaN               NaN
199          39           NaN             NaN               NaN

     Unnamed: 0.1.1.1.1                            title  type
0                   0.0      속보 서울고검 재판부 사찰의혹 윤석열 무혐의 처분     2
1                   1.0       서울고검 판사 문건 윤석열 총장에  무혐의 처분     2
2                   2.0            서울고검 윤석열 판사 사찰 무혐의 처분     2
3                   3.0          서울고검 윤석열 판사 사찰 무혐의 처분종합     2
4                   4.0      속보 고양시 태평양무도장 명 집단감염방역조치 위반     2
..                  ...                              ...   ...
195                 NaN         선거법 위반 이선호 울주군수 직위상실형 피해     2
196                 NaN             잔혹 동물학대에 동물보호법 촘촘해진다     2
197                 NaN     동물학대 처벌 강화 최대 징역 년  년유기해도 처벌     2
198                 NaN        용인 살 여아 이모 부부 폭행물고문으로 숨졌다     2
199                 NaN  이모집 맡겨진 살 아이 온몸 멍든채 욕조서 숨져폭행 조사     2

[200 rows x 7 columns]
0          속보 서울고검 재판부 사찰의혹 윤석열 무혐의 처분
1           서울고검 판사 문건 윤석열 총장에  무혐의 처분
2                서울고검 윤석열 판사 사찰 무혐의 처분
3              서울고검 윤석열 판사 사찰 무혐의 처분종합
4          속보 고양시 태평양무도장 명 집단감염방역조치 위반
                    ...
195           선거법 위반 이선호 울주군수 직위상실형 피해
196               잔혹 동물학대에 동물보호법 촘촘해진다
197       동물학대 처벌 강화 최대 징역 년  년유기해도 처벌
198          용인 살 여아 이모 부부 폭행물고문으로 숨졌다
199    이모집 맡겨진 살 아이 온몸 멍든채 욕조서 숨져폭행 조사
Name: title, Length: 200, dtype: object 0      2
1      2
2      2
3      2
4      2
      ..
195    2
196    2
197    2
198    2
199    2
Name: type, Length: 200, dtype: int64
(74, 7)
    Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1  \
0            0           0.0             0.0               0.0
1            1           1.0             1.0               1.0
2            2           2.0             2.0               2.0
3            3           3.0             3.0               3.0
4            4           4.0             4.0               4.0
..         ...           ...             ...               ...
69          11           NaN             NaN               NaN
70          12           NaN             NaN               NaN
71          13           NaN             NaN               NaN
72          14           NaN             NaN               NaN
73          15           NaN             NaN               NaN

    Unnamed: 0.1.1.1.1                            title  type
0                  0.0            황희 장관후보자 청문회가족여행 등 쟁점     3
1                  1.0     황희 신속  검진 일반에 승인되면 트래블 버블 가능     3
2                  2.0  황희 코로나 고통 큰 문화체육관광 분야 회복에 주력할 것     3
3                  3.0        황희 후보자 코로나 피해 회복문화 뉴딜에 주력     3
4                  4.0       내일 아침까지 추위낮부터 기온 올라 포근한 겨울     3
..                 ...                              ...   ...
69                 NaN  황희 수자원공사 간부 고액 후원 의혹에 명단 보지 않는다     3
70                 NaN     벤츠 디젤라인 국내 판매 중단올해 판매 타격 불가피     3
71                 NaN    벤츠 디젤차량 고객 인도 일시중단내부 확인 거쳐 재개     3
72                 NaN            국산 애니 레드슈즈 아카데미상에 도전장     3
73                 NaN         한국 애니메이션 레드슈즈 아카데미상에 도전장     3

[74 rows x 7 columns]
0               황희 장관후보자 청문회가족여행 등 쟁점
1        황희 신속  검진 일반에 승인되면 트래블 버블 가능
2     황희 코로나 고통 큰 문화체육관광 분야 회복에 주력할 것
3           황희 후보자 코로나 피해 회복문화 뉴딜에 주력
4          내일 아침까지 추위낮부터 기온 올라 포근한 겨울
                   ...
69    황희 수자원공사 간부 고액 후원 의혹에 명단 보지 않는다
70       벤츠 디젤라인 국내 판매 중단올해 판매 타격 불가피
71      벤츠 디젤차량 고객 인도 일시중단내부 확인 거쳐 재개
72              국산 애니 레드슈즈 아카데미상에 도전장
73           한국 애니메이션 레드슈즈 아카데미상에 도전장
Name: title, Length: 74, dtype: object 0     3
1     3
2     3
3     3
4     3
     ..
69    3
70    3
71    3
72    3
73    3
Name: type, Length: 74, dtype: int64
(100, 7)
    Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1  \
0            0           0.0             0.0               0.0
1            1           1.0             1.0               1.0
2            2           2.0             2.0               2.0
3            3           3.0             3.0               3.0
4            4           4.0             4.0               4.0
..         ...           ...             ...               ...
95          15           NaN             NaN               NaN
96          16           NaN             NaN               NaN
97          17           NaN             NaN               NaN
98          18           NaN             NaN               NaN
99          19           NaN             NaN               NaN

    Unnamed: 0.1.1.1.1                                     title  type
0                  0.0                카카오 지난해 매출 사상 최대연 조원 시대 열어     4
1                  1.0  카카오 연매출 조 돌파 의장은 재산 기부기업가치 높여 더 나은 사회로종합     4
2                  2.0                     카카오 톡비즈 날개 달고 영업익 억종합     4
3                  3.0                  카카오 지난해 매출 조원 돌파역대 최대 실적     4
4                  4.0           언택트 수혜 못 본  지난해 실적 통신 사 중 가장 부진     4
..                 ...                                       ...   ...
95                 NaN                  엔씨소프트 블소 출시 본격 행보액션성 극대화     4
96                 NaN             올해 콜센터 사업도 본격 진출부문 지난해보다 더 성장     4
97                 NaN                    올해  전년과 유사 미디어 부문 확대컨콜     4
98                 NaN                올해  가입자 비중 전체 핸드셋 까지 성장할 것     4
99                 NaN                       올해  가입자전체 핸드셋  기대컨콜     4

[100 rows x 7 columns]
0                   카카오 지난해 매출 사상 최대연 조원 시대 열어
1     카카오 연매출 조 돌파 의장은 재산 기부기업가치 높여 더 나은 사회로종합
2                        카카오 톡비즈 날개 달고 영업익 억종합
3                     카카오 지난해 매출 조원 돌파역대 최대 실적
4              언택트 수혜 못 본  지난해 실적 통신 사 중 가장 부진
                        ...
95                    엔씨소프트 블소 출시 본격 행보액션성 극대화
96               올해 콜센터 사업도 본격 진출부문 지난해보다 더 성장
97                      올해  전년과 유사 미디어 부문 확대컨콜
98                  올해  가입자 비중 전체 핸드셋 까지 성장할 것
99                         올해  가입자전체 핸드셋  기대컨콜
Name: title, Length: 100, dtype: object 0     4
1     4
2     4
3     4
4     4
     ..
95    4
96    4
97    4
98    4
99    4
Name: type, Length: 100, dtype: int64